//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StateInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Association is not found..
        /// </summary>
        public static string ApplicationAssociationNotFound {
            get {
                return ResourceManager.GetString("ApplicationAssociationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid date..
        /// </summary>
        public static string DateIsInvalid {
            get {
                return ResourceManager.GetString("DateIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yy H:mm:ss.
        /// </summary>
        public static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd, MMM dd, yyyy HH:mm tt.
        /// </summary>
        public static string DayDateTimeFormat {
            get {
                return ResourceManager.GetString("DayDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id is invalid..
        /// </summary>
        public static string IdInvalid {
            get {
                return ResourceManager.GetString("IdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is invalid..
        /// </summary>
        public static string NameInvalid {
            get {
                return ResourceManager.GetString("NameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} entered must be a value greater than zero..
        /// </summary>
        public static string NumberMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("NumberMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is empty..
        /// </summary>
        public static string ParameterEmpty {
            get {
                return ResourceManager.GetString("ParameterEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is invalid..
        /// </summary>
        public static string ParameterInvalid {
            get {
                return ResourceManager.GetString("ParameterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is null..
        /// </summary>
        public static string ParameterNull {
            get {
                return ResourceManager.GetString("ParameterNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent Id is invalid..
        /// </summary>
        public static string ParentIdInvalid {
            get {
                return ResourceManager.GetString("ParentIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Records Center name is invalid..
        /// </summary>
        public static string RecordsCenterInvalid {
            get {
                return ResourceManager.GetString("RecordsCenterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Records Center &apos;{0}&apos; could not be found..
        /// </summary>
        public static string RecordsCenterNotFound {
            get {
                return ResourceManager.GetString("RecordsCenterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snippet criteria is invalid..
        /// </summary>
        public static string SnippetCriteriaInvalid {
            get {
                return ResourceManager.GetString("SnippetCriteriaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snippet description is invalid..
        /// </summary>
        public static string SnippetDescriptionInvalid {
            get {
                return ResourceManager.GetString("SnippetDescriptionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snippet field name already exists for this subtransaction..
        /// </summary>
        public static string SnippetFieldNameAlreadyExists {
            get {
                return ResourceManager.GetString("SnippetFieldNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested snippet field was not found..
        /// </summary>
        public static string SnippetFieldNotFound {
            get {
                return ResourceManager.GetString("SnippetFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field type has {1} property which is invalid..
        /// </summary>
        public static string SnippetFieldParameterInvalidForType {
            get {
                return ResourceManager.GetString("SnippetFieldParameterInvalidForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snippet format is invalid..
        /// </summary>
        public static string SnippetFormatInvalid {
            get {
                return ResourceManager.GetString("SnippetFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snippet name already exists for this Records Center..
        /// </summary>
        public static string SnippetNameAlreadyExists {
            get {
                return ResourceManager.GetString("SnippetNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The snippet name is invalid..
        /// </summary>
        public static string SnippetNameInvalid {
            get {
                return ResourceManager.GetString("SnippetNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested snippet was not found..
        /// </summary>
        public static string SnippetNotFound {
            get {
                return ResourceManager.GetString("SnippetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified error occurred..
        /// </summary>
        public static string UnspecifiedError {
            get {
                return ResourceManager.GetString("UnspecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the required authorization to perform this action..
        /// </summary>
        public static string UserIsUnauthorized {
            get {
                return ResourceManager.GetString("UserIsUnauthorized", resourceCulture);
            }
        }
    }
}
